name: Sync Fork Automatically

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    # Dôležité: toto dá GITHUB_TOKEN práva pre zápis do repa.
    permissions:
      contents: write

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          # Tu je dobré overiť, že naozaj
          # používate GITHUB_TOKEN s write právami
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get Original Repository URL
        id: get_upstream
        run: |
          UPSTREAM_URL=$(jq -r '.parent.html_url' <<< \
            $(curl -s "https://api.github.com/repos/${{ github.repository }}"))
          echo "UPSTREAM_URL=$UPSTREAM_URL" >> $GITHUB_ENV

      - name: Add Upstream Remote and Fetch
        run: |
          git remote add upstream $UPSTREAM_URL || true
          git fetch upstream

      - name: Detect Default Branch
        id: detect_branch
        run: |
          DEFAULT_BRANCH=$(git remote show upstream | awk '/HEAD branch/ {print $NF}')
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Sync Fork with Upstream
        run: |
          git checkout $DEFAULT_BRANCH
          git merge upstream/$DEFAULT_BRANCH --no-edit || git merge --abort
          git push origin $DEFAULT_BRANCH
